site_name: Mathod
nav:
    - Home: index.md
    - Kubernetes: kubernetes.md
    - 'AUTOMATION/CONFIGURATION':
        - 'Terraform': 'terraform/foreword.md'
        - 'Ansible': 'ansible/foreword.md'
    - 'PROVIDERS':
        - 'AWS': 'aws/foreword.md'
    - 'APPS':
        - 'ArgoCD': 'argocd/foreword.md'
        - 'Istio': 'istio/foreword.md'
        - 'Keda': 'keda/foreword.md'
        - 'Karpenter': 'karpenter/foreword.md'
        - 'Prometheus': 'prometheus/foreword.md'
        - 'Grafana': 'grafana/foreword.md'
        - 'Harbor': 'harbor/foreword.md'
        - 'WireGuard': 'wireguard/foreword.md'
    
    - 'GITLAB' :
        - 'Foreword': 'gitlab/foreword.md'
        - 'Usecase': 'gitlab/usecase.md'
        - 'Mattermost': 'gitlab/mattermost.md'
    - 'OTHERS': 
        - 'Glossary': glossary.md
        - 'About': about.md
theme: readthedocs