site_name: Mathod
nav:
    - Home: index.md
    - Kubernetes: kubernetes.md
    - ArgoCD: argocd/foreword.md
    - Istio: istio.md
    - AWS: aws.md
    - Ansible: ansible.md
    - Wireguard: wireguard.md
    - Mattermost: mattermost.md
    - Harbor: harbor.md
    - Keda: keda.md
    - Karpenter: karpenter.md
    - GitLab: gitlab.md
    - Glossary: glossary.md
    - About: about.md
theme: readthedocs